### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [maximus64/sd_rgb500_cfw#2]
Hello!

I found this project from https://hackaday.com/2022/12/11/laser-projector-needs-hardware-hack-after-software-mod/

Could you please add information about the license of this repository — is it allowed to copy, change and use the source code, design files and images in any purpose?
It would be great to see any popular open source license.

**Comment by maximus64** [comment]
I have added the license information. The project is released under [Unlicense](http://unlicense.org/) license. Thanks :)

**Comment by vazhnov** [comment]
Unlicense — amazing!
@maximus64, thank you!
